extends:
- openlayers
- .eslintrc-es6.yaml
env:
    jquery: true
    jasmine: true
rules:
    no-console: 0
    # temporary disable some es6 errors
    prefer-arrow-callback: 0
    prefer-template: 0
    prefer-spread: 0
    prefer-rest-params: 0
    object-shorthand: 0
globals:
    angular: false
    goog: false
    d3: false
    Bloodhound: false
    ol: false
    proj4: false
    saveAs: false
    ngeo: false
    gmf: false
    app: false
    gmfapp: false
    inject: false
    jsts: false
