dist: trusty
sudo: false

language: node_js

env:
  global:
  - CXX=g++-4.8
  - secure: "l/McmiK4djffT04/+5MxW9sy4yO80Rf6vq+nZb5P647A6pXpPLdoRLGo50CtYRiKnFLiChHk2QxUOspeKuIKE+UQAm9dGmyMgfYkj/jwxIBd0YQqavaGzoWo5U1ZSGKeVd3kJlIaUJyLlnKbBOmFCY00c4JLveAagsV53lbephY="

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - g++-4.8
    - python-virtualenv
    - google-chrome-stable

matrix:
  include:
  # Just do the tests
  - node_js: "4"
    env: NODE=4
  # Test the examples in white space mode on the pull requests
  - node_js: "6"
    env: DEVELOPMENT=TRUE
  # Deploy the examples in advance mode on the commit on a branch
  - node_js: "6"
    env: EXAMPLES=TRUE

cache:
  apt: true
  directories:
  - node_modules

before_install:
- npm prune
- if [ "${TRAVIS_PULL_REQUEST}" = false ]; then IS_PR=FALSE; else IS_PR=TRUE; fi
- if [ ${TRAVIS_REPO_SLUG}-${IS_PR} = camptocamp/ngeo-FALSE ]; then openssl aes-256-cbc -K $encrypted_66d875d20fac_key -iv $encrypted_66d875d20fac_iv -in secrets.tar.enc -out secrets.tar -d; fi
- if [ ${TRAVIS_REPO_SLUG}-${IS_PR} = camptocamp/ngeo-FALSE ]; then tar xvf secrets.tar; fi
- if [ ${TRAVIS_REPO_SLUG}-${IS_PR} = camptocamp/ngeo-FALSE ]; then cp .transifexrc $HOME/.transifexrc; fi
- if [ ${TRAVIS_REPO_SLUG}-${IS_PR} = camptocamp/ngeo-FALSE ]; then cp ngeo_deploy_key $HOME/.ssh/id_rsa; fi
- if [ ${TRAVIS_REPO_SLUG}-${IS_PR} = camptocamp/ngeo-FALSE ]; then chmod 600 $HOME/.ssh/id_rsa; fi
- git config --global user.name "Travis"
- git config --global user.email "travis@travis-ci.org"

script:
- /opt/google/chrome/chrome --version
- export CHROME_BIN=/opt/google/chrome/chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- if [ "${IS_PR}" != "FALSE" ]; then git fetch origin ${TRAVIS_BRANCH}:${TRAVIS_BRANCH}; fi
- if [ "${IS_PR}" != "FALSE" ]; then git diff --check ${TRAVIS_BRANCH} --; fi
- if [ "`git grep @fileoverview src contribs`" != "" ]; then echo "Using @fileoverview breaks the documentation main page"; FALSE; fi
- if [ "`git grep @example src contribs`" != "" ]; then echo "We don't use @example to have the example in the description"; FALSE; fi
- make git-attributes
- if [ "${EXAMPLES}" != TRUE ]; then make lint; fi

- if [ "${DEVELOPMENT}-${IS_PR}" = TRUE-TRUE ]; then buildtools/test_examples.py; fi
- if [ "${DEVELOPMENT}-${IS_PR}" = TRUE-TRUE ]; then make dist/ngeo.js; fi
- if [ "${DEVELOPMENT}-${IS_PR}" = TRUE-TRUE ]; then make dist/ngeo-debug.js; fi
- if [ "${DEVELOPMENT}-${IS_PR}" = TRUE-TRUE ]; then make dist/gmf.js; fi

- if [ "${DEVELOPMENT}" = TRUE ]; then make test; fi
- if [ "${NODE}" = 4 ]; then make test; fi

after_success:
- cat .build/coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js
- export GIT_BRANCH=${TRAVIS_BRANCH}
- echo "_auth = ${NPM_AUTH}" > ~/.npmrc
- echo "email = stephane.brunner@camptocamp.com" >> ~/.npmrc
- make .build/python-venv
- .build/python-venv/bin/pip install jsongrep
- export PACKAGE_VERSION=`.build/python-venv/bin/jsongrep -e version package.json`

deploy:
- provider: script
  script: make gh-pages
  skip_cleanup: true
  on:
    repo: camptocamp/ngeo
    all_branches: true
    condition: '"${EXAMPLES}-${IS_PR}" = TRUE-FALSE'
- provider: script
  script: npm publish
  skip_cleanup: true
  on:
    node: "4"
    repo: camptocamp/ngeo
    tags: true
    condition: '"${PACKAGE_VERSION}" == "${TRAVIS_TAG}"'
- &transifex
  provider: script
  script: make transifex-send
  skip_cleanup: true
  on:
    repo: camptocamp/ngeo
    branch: master
    node: "4"
- <<: *transifex
  on:
    repo: camptocamp/ngeo
    branch: 2.0
    node: "4"
